# Generated by Django 5.1.2 on 2024-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('data_nascimeto', models.DateField(verbose_name='Data nascimento')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('telefonte', models.BigIntegerField(help_text='inserir numero com DDD', verbose_name='telefone')),
            ],
        ),
    ]
