# Generated by Django 5.1.2 on 2024-12-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MightyLeaf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
